sudo: false
language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
script:
  - nosetests --with-coverag tests/unit
after_success: coveralls --verbose
